version: "3.3"

services:
  go:
      build: .
      ports:
          - "8080" # this is port i'm exposing in the container

  proxy:
      image: nginx:latest
      ports:
          - "80:80" # host:container
          - "443:443"
      volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
          # connect host's ./nginx.conf with container's nginx.conf
          # :ro == read only perms in container
      links:
          - go:app # [other container]:[alias in this container]
            # creates environment variables in proxy container
            # with ip and port info for go container
            # also creates entries in /etc/hosts with ip info
  
  redis:
    image: "redis:alpine"